module.exports = {
    transactions: [
        {
            id: 1,
            amount: 1000,
            operation_type_name: 'credito',
            amount_available_on_date: '2021-02-15',
            withdraw_status: 'done',
            withdraw_date: '2021-02-16',
        },
        {
            id: 2,
            amount: 135,
            operation_type_name: 'credito',
            amount_available_on_date: '2021-01-02',
            withdraw_status: 'available',
            withdraw_date: null,
        },
        {
            id: 3,
            amount: 681,
            operation_type_name: 'debito',
            amount_available_on_date: '2021-01-30',
            withdraw_status: 'available',
            withdraw_date: null,
        },
        {
            id: 4,
            amount: 3100,
            operation_type_name: 'debito',
            amount_available_on_date: '2021-02-09',
            withdraw_status: 'available',
            withdraw_date: null,
        },
        {
            id: 5,
            amount: 3100,
            operation_type_name: 'debito',
            amount_available_on_date: '2021-01-21',
            withdraw_status: 'available',
            withdraw_date: null,
        },
        {
            id: 6,
            amount: 100,
            operation_type_name: 'debito',
            amount_available_on_date: '2021-05-15',
            withdraw_status: 'unavailable',
            withdraw_date: null,
        },
        {
            id: 7,
            amount: 50,
            operation_type_name: 'credito',
            amount_available_on_date: '2021-02-15',
            withdraw_status: 'available',
            withdraw_date: null,
        },
        {
            id: 8,
            amount: 10,
            operation_type_name: 'debito',
            amount_available_on_date: '2021-02-08',
            withdraw_status: 'done',
            withdraw_date: '2021-02-09',
        },
        {
            id: 9,
            amount: 350,
            operation_type_name: 'credito',
            amount_available_on_date: '2021-02-25',
            withdraw_status: 'done',
            withdraw_date: '2021-02-25',
        },
        {
            id: 10,
            amount: 900,
            operation_type_name: 'debito',
            amount_available_on_date: '2021-02-22',
            withdraw_status: 'available',
            withdraw_date: null,
        },
        {
            id: 11,
            amount: 42,
            operation_type_name: 'debito',
            amount_available_on_date: '2021-02-09',
            withdraw_status: 'available',
            withdraw_date: null,
        },
        {
            id: 12,
            amount: 90,
            operation_type_name: 'credito',
            amount_available_on_date: '2021-03-01',
            withdraw_status: 'available',
            withdraw_date: null,
        }
    ]
}